### ISSUE TITLE
Target domain for mini ImageNet and tiered ImageNet

### ISSUE THREAD

**Issue by MyeongJin-Kim** [dingmyu/DAPN#1]
Do you have plan to release datasets of target domain for mini ImageNet and tiered ImageNet?

**Comment by dingmyu** [comment]
Hi, we provide the datasets of target domain in Google Drive, [miniImageNet](https://drive.google.com/file/d/1Yxzw2kJarXCV2tldKzXt6rlGqcLuv24W), [tieredImageNet](https://drive.google.com/file/d/1Unqwgiuoy7br8vKiEZo8Jhib-eNDxc5p).

**Comment by ljjcoder** [comment]
@dingmyu Thank you for your excellent work. How is your miniImagenet data set generated? As far as I know, different methods produce miniImagenet in different ways. Some people use the center crop method and then scale to 84x84. However, some methods directly resize to 84x84, and some methods directly randomly crop and then scale to 84x84 during training?
