### ISSUE TITLE
DomainNet split

### ISSUE THREAD

**Issue by topwasu** [dingmyu/DAPN#4]
Hi!

I am wondering if it is possible for you to release the splits of DomainNet used in the paper?

**Comment by dingmyu** [comment]
Hi,

In this work, we take the real photo domain in DomainNet as the source domain and the sketch domain as the target domain.

You can download from the official website [Here](http://ai.bu.edu/M3SDA/)

Mingyu

**Comment by topwasu** [comment]
Hi,

Sorry if my initial question was unclear. I meant the class splits. Like, in the paper, you split the classes into 275 classes for Cs, 55 classes for Cd, and 70 classes for Ct. I want to know what Cs, Cd, and Ct of DomainNet are. (Come to think of it, the three numbers also don't add up to 345 which is the total number of classes of DomainNet. How exactly did you do the split?)

**Comment by dingmyu** [comment]
Hi, 

Sorry for the typo. The number of training classes is 220.

I have uploaded the train/val/test split in this repo, see [here](https://github.com/dingmyu/DAPN/tree/master/dataset/DomainNet). Thanks.

Mingyu

**Comment by topwasu** [comment]
Thank you!
